### ISSUE TITLE
Missing URI foregroundservice

### ISSUE THREAD

**Issue by BrandonKroes** [OIToDo/CHPE#32]
The intent of the foregroundservice needs the path (string and uri) of the selected gallery video with i/o flags. Currently there's a new intent being made by the on click listener for the a_Loading.class either this needs to be fixed or the openVideoGallery intent needs to be passed along.

Test case: https://gist.github.com/BrandonKroes/72a91a31a64fac6696cc1f2b14c8f1f7#file-foregroundservice-java-L61

**Comment by nicovanbentum** [comment]
Fixed in https://github.com/OIToDo/CHPE/commit/82fb9aae6f7fd4fe2cd8ba0aca250626e5e115e9 .
